# Tokyo Night Theme Configuration

# Colors
background = rgba(1A1B26FF)
base = rgba(16161EFF)
text = rgba(C0CAF5FF)
alternate_base = rgba(24283BFF)
bright_text = rgba(A9B1D6FF)
accent = rgba(7DCFFFFF)
accent_secondary = rgba(7AA2F7FF)
