# Builtin Monitor
monitor = eDP-1, preferred, auto, 2

# Home Widescreen Monitor
monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD., 3440x1440@144.00Hz, auto-left, 1
# monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD., 2560x1440@144.00Hz, auto-left, 1
# monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD., disabled
# CS2
# monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD., 2560x1440@144.00Hz, auto-left, 1

# Home TV 
monitor = desc:Samsung Electric Company SAMSUNG, 3840x2160@30.00Hz, auto-left, 2

# Default Quick Plug
monitor = , preferred, auto-left, 2

# Work Monitors
monitor = desc:Dell Inc. DELL S3422DWG HFG4KK3, 3440x1440@143.97Hz, -3440x-500, 1
