windowrule {
    name = firefox-pip
    match:class = firefox-nightly
    match:title = Picture-in-Picture

    float = on
    pin = on
    size = 320 180
    move = 4 (monitor_h-window_h-4)
    no_initial_focus = on
    content = video
}


windowrule {
    name = Deadlock
    match:class = steam_app_1422450
    match:title = Deadlock

    center = on
}
