[keybinds]
next = "ctrl n"
previous = "ctrl p"


[providers]
default = ["desktopapplications", "runner"] # providers to be queried by default
empty = ["desktopapplications"]             # providers to be queried when query is empty

[providers.runner]
start = "enter"
start_terminal = "ctrl enter"
# generic_entry = true
