return {
	-- {
	-- 	"milanglacier/minuet-ai.nvim",
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 	},
	-- 	opts = {
	-- 		blink = { enable_auto_complete = true },
	-- 		model = "gemini-2.0-flash",
	-- 		stream = true,
	-- 		provider = "gemini",
	-- 		api_key = "GEMINI_API_KEY",
	-- 		end_point = "https://generativelanguage.googleapis.com/v1beta/models",
	-- 		provider_options = {
	-- 			gemini = {
	-- 				optional = {
	-- 					generationConfig = {
	-- 						maxOutputTokens = 256,
	-- 						-- When using `gemini-2.5-flash`, it is recommended to entirely
	-- 						-- disable thinking for faster completion retrieval.
	-- 						thinkingConfig = {
	-- 							thinkingBudget = 0,
	-- 						},
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- },
}
