#!/usr/bin/env lua

-- Source the Sketchybar so
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Load the sketchybar-package and prepare the helper binaries
require("init")
