[settings]

[settings.npm]
package_manager = "pnpm"

[tools]
# Langues / PMs
dotnet = "latest"
go = "latest"
lua = "latest"
node = "latest"
pnpm = "latest"
rust = "latest"
uv = "latest"

# LS / Linters / Formatters
## Bash
"npm:bash-language-server" = "latest"
shellcheck = "latest"
shfmt = "latest"
## Go
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
## Lua
lua-language-server = "latest"
stylua = "latest"
## Markdown
marksman = "latest"
## Python
ruff = "latest"
ty = "latest"
## Typescript
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
## TOML
taplo = "latest"
## YAML
"npm:yaml-language-server" = "latest"
 
# Bash Tools
bat = "latest"
bottom = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
ripgrep = "latest"
sheldon = "latest"
starship = "latest"
tree-sitter = "latest"
tokei = "latest"
usage = "latest"

# Dev tools
delta = "latest"
ffmpeg = "latest"
github-cli = "latest"
neovim = "nightly"
pi = "latest"
zellij = "latest"
