[settings]

[settings.npm]
package_manager = "pnpm"

# [bootstrap.brew.taps]
# ""

[bootstrap.packages]
"brew:mise" = "latest"
"brew:neovim" = "latest"
"brew:tailscale" = "latest"
"brew:borders" = "latest"
"brew:sketchybar" = "latest"
"brew:docker" = "latest"
#Brew Casks
"brew-cask:font-commit-mono-nerd-font" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:hammerspoon" = "latest"
"brew-cask:nikitabobko/tap/aerospace" = "latest"
"brew-cask:dimentium/autoraise/autoraiseapp" = "latest"
"brew-cask:unnaturalscrollwheels" = "latest"
"brew-cask:firefox@nightly" = "latest"
"brew-cask:docker-desktop" = "latest"

[tools]
# Langues / PMs
dotnet = "latest"
go = "latest"
lua = "latest"
node = "latest"
pnpm = "latest"
rust = "latest"
uv = "latest"

# LS / Linters / Formatters
## Bash
shellcheck = "latest"
shfmt = "latest"
## Go
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
## Lua
lua-language-server = "latest"
stylua = "latest"
## Python
ruff = "latest"
ty = "latest"
## Typescript
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
## TOML
taplo = "latest"
 
# Bash Tools
bat = "latest"
bottom = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
ripgrep = "latest"
sheldon = "latest"
starship = "latest"
tree-sitter = "latest"
tokei = "latest"

# Dev tools
delta = "latest"
ffmpeg = "latest"
github-cli = "latest"
pi = "0.80.10"
zellij = "latest"
