[settings]

[tools]
# Langues / PMs
dotnet = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
node = "latest"
pnpm = "latest"
rust = "latest"
uv = "latest"
 
# Bash Tools
bat = "latest"
bottom = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
lsd = "latest"
