[bootstrap.packages]
"pacman:7zip" = "latest"
"pacman:acpid" = "latest"
"pacman:base" = "latest"
"pacman:base-devel" = "latest"
"pacman:bolt" = "latest"
"pacman:brightnessctl" = "latest"
"pacman:btrfs-progs" = "latest"
"pacman:bun" = "latest"
"pacman:chromium" = "latest"
"pacman:cliphist" = "latest"
"pacman:cuda" = "latest"
"pacman:cups" = "latest"
"pacman:cups-browsed" = "latest"
"pacman:dolphin-emu" = "latest"
"pacman:dunst" = "latest"
"pacman:expac" = "latest"
"pacman:firefox-nightly" = "latest"
"pacman:foot" = "latest"
"pacman:fwupd" = "latest"
"pacman:fzf" = "latest"
"pacman:gamemode" = "latest"
"pacman:git" = "latest"
"pacman:git-lfs" = "latest"
"pacman:gnome-tweaks" = "latest"
"pacman:grim" = "latest"
"pacman:intel-ucode" = "latest"
"pacman:kicad" = "latest"
"pacman:kvantum" = "latest"
"pacman:lib32-nvidia-utils" = "latest"
"pacman:lib32-pipewire" = "latest"
"pacman:lib32-pipewire-jack" = "latest"
"pacman:libreoffice-fresh" = "latest"
"pacman:libvncserver" = "latest"
"pacman:linux" = "latest"
"pacman:linux-firmware" = "latest"
"pacman:man-db" = "latest"
"pacman:man-pages" = "latest"
"pacman:mise" = "latest"
"pacman:nemo" = "latest"
"pacman:nemo-fileroller" = "latest"
"pacman:networkmanager" = "latest"
"pacman:nmap" = "latest"
"pacman:noto-fonts-cjk" = "latest"
"pacman:noto-fonts-emoji" = "latest"
"pacman:noto-fonts-extra" = "latest"
"pacman:nvidia-open" = "latest"
"pacman:nvidia-settings" = "latest"
"pacman:nvidia-utils" = "latest"
"pacman:obs-studio" = "latest"
"pacman:openssh" = "latest"
"pacman:otf-commit-mono-nerd" = "latest"
"pacman:pacutils" = "latest"
"pacman:pavucontrol" = "latest"
"pacman:pipewire" = "latest"
"pacman:pipewire-alsa" = "latest"
"pacman:pipewire-audio" = "latest"
"pacman:pipewire-jack" = "latest"
"pacman:pipewire-pulse" = "latest"
"pacman:power-profiles-daemon" = "latest"
"pacman:protontricks" = "latest"
"pacman:qbittorrent" = "latest"
"pacman:qt5-wayland" = "latest"
"pacman:remmina" = "latest"
"pacman:satty" = "latest"
"pacman:scx-scheds" = "latest"
"pacman:scx-tools" = "latest"
"pacman:slurp" = "latest"
"pacman:sof-firmware" = "latest"
"pacman:steam" = "latest"
"pacman:sudo" = "latest"
"pacman:tailscale" = "latest"
"pacman:texinfo" = "latest"
"pacman:trash-cli" = "latest"
"pacman:udiskie" = "latest"
"pacman:udisks2" = "latest"
"pacman:ufw" = "latest"
"pacman:unrar" = "latest"
"pacman:uwsm" = "latest"
"pacman:vim" = "latest"
"pacman:wget" = "latest"
"pacman:zip" = "latest"
"pacman:zsh" = "latest"
